fix(web-app): update pnpm-lock.yaml because of a production error
Error: ERR_PNPM_OUTDATED_LOCKFILE  Cannot install with frozen-lockfile because pnpm-lock.yaml is not up to date with apps/web-app/package.json